apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cicd-app-analysis
spec:
  metrics:
    - name: error-rate
      interval: 10s
      count: 1
      failureLimit: 1
      successCondition: result[0] < 0.05
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            max(app_error_rate)

    - name: p99-latency
      interval: 10s
      count: 1
      failureLimit: 1
      successCondition: result[0] < 1
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            max(app_p99_latency_seconds)