apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: cicd-app
          image: reemahmad11/cicd-app:5d74f17bbd254ce396515f55e300dd92149d35a3
          imagePullPolicy: Always
          ports:
            - containerPort: 5000