apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cicd-app

spec:
  replicas: 5

  selector:
    matchLabels:
      app: cicd-app

  template:
    metadata:
      labels:
        app: cicd-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"

    spec:
      containers:
        - name: cicd-app
          image: reemahmad11/cicd-app:metrics-good
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

  strategy:
    canary:
      steps:
        - setWeight: 20
        - analysis:
            templates:
              - templateName: cicd-app-analysis

        - pause: {}

        - setWeight: 50
        - analysis:
            templates:
              - templateName: cicd-app-analysis

        - pause: {}

        - setWeight: 100