apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cicd-app-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: cicd-app-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: cicd-app-secret